apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  initContainers:
    - name: kaniko-init
      image: alpine
      args:
        - "sh"
        - "-c"
        - "while true; do sleep 1; if [ -f /tmp/complete ]; then break; fi done"
      volumeMounts:
        - name: build-context
          mountPath: /kaniko/build-context
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=Dockerfile"
        - "--context=dir:///kaniko/build-context"
        - "--destination=#REPOSITORY#/#NAMEPACE#/#IMAGE#:#TAG#"
        - "--skip-tls-verify"
      volumeMounts:
        - name: build-context
          mountPath: /kaniko/build-context
        - name: docker-config
          mountPath: /kaniko/.docker
  hostAliases:
    - ip: "9.20.194.150"
      hostnames:
      - "mycluster.icp"
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
    - name: build-context
      emptyDir: {}
