kind: Deployment
metadata:
  name: getcustomer-#TAG#
  namespace: #NAMESPACE#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getcustomer
  template:
    metadata:
      labels:
        app: getcustomer
    spec:
      containers:
      - name: getcustomer
        image: mycluster.icp:8500/#NAMESPACE#/getcustomer:#TAG#
        resources:
          limits:
            memory: "500Mi"
            cpu: "4"
          requests:
            memory: "300Mi"
            cpu: "2"
        ports:
        - containerPort: 9080
