apiVersion: v1
kind: Service
metadata:
  name: getcustomer-nodeport-service-#TAG#
  namespace: #NAMESPACE#
spec:
  externalTrafficPolicy: Cluster
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: getcustomer
